src/app/app-routing.module.ts, src/app/map-location/map-location.service.ts, src/app/route/route-detail/route-detail.component.ts, src/app/route/route-edit/route-edit.component.html, src/app/route/route-edit/route-edit.component.ts, src/app/route/route-list/route-list.component.ts, src/app/route/route.service.ts, src/app/route/routes/routes.component.html, src/app/route/routes/routes.component.ts
Przycisk dodawania nowej trasy w prawym górnym rogu, obok mapy. Dodawanie nowego route, bez uzytkownika (user == null). W przyszlosci bedziemy sciagac uzytkownika z log-in component albo cos w tym stylu, bo tyko zalogowany moze dodawac trasy. Trzeba takze dorobic dodawanie pointow do routea
=> 11 dodawanie nowej trasy

src/app/route/route-edit/route-edit.component.html, src/app/route/route-edit/route-edit.component.ts, src/app/route/route.service.ts
Usuwanie trasy dziala (z poziomu edycji trasy). Po nacisnieciu DELETE wyskakuje popup każący potwierdzic decyzje. OK wysyla zapytanie Delete, Cancel wraca do okna edycji, trasa nie zostaje usunieta
=> 13 usuwanie tras

src/app/app.component.html, src/app/header/header.component.css, src/app/header/header.component.html, src/app/route/route-detail/route-detail.component.html, src/app/route/route-detail/route-detail.component.ts, src/app/route/route-detail/route-detail.service.ts, src/app/route/route-list/route-list.component.html, src/app/route/routes/routes.component.css, src/app/route/routes/routes.component.html, src/app/route/routes/routes.component.ts, src/app/shared/map/map.component.html, src/app/shared/map/map.component.ts, src/app/shared/map/map.service.ts, src/app/shared/side-panel/side-panel.component.css, src/app/shared/side-panel/side-panel.component.html, src/app/shared/side-panel/side-panel.component.ts
zmieniono wygląd strony
bugi ktore usunieto:
kliknij na routa
wyswietl szczegoly
kliknij ikonke WayToGo
rozwin liste rotow
(pusto)
na malych urzadzeniach navbar i panel button sie bugują
wspolrzedne są uciete
Wybierz trase wyswietlaja sie punkty, 
kliknij routes. 
punkty wciaz sie wyswietlaja
=> 19 dodanie bocznego panelu i zmiana ukladu

src/app/app-routing.module.ts, src/app/header/header.component.html, src/app/route/route-detail/route-detail.component.html, src/app/route/route-detail/route-detail.component.ts, src/app/route/route-detail/route-detail.service.ts, src/app/route/route-edit/route-edit.component.ts, src/app/route/route-info/route-info.component.css, src/app/route/route-info/route-info.component.html, src/app/route/route-info/route-info.component.ts, src/app/route/route-list/route-item/route-item.component.html, src/app/route/route-list/route-item/route-item.component.ts, src/app/route/route-list/route-list.component.html, src/app/route/route-list/route-list.component.ts, src/app/route/routes/routes.component.html, src/app/route/routes/routes.component.ts, src/app/shared/side-panel/side-panel.component.ts
chwała wielkiemu słońcu,
Zimeniłem rooting i zminiłem sposób wyświetlania details, listy i edycji
=> changed details and rooting

src/app/route/route-info/route-info.component.html, src/app/route/route-list/route-list.component.css, src/app/route/route-list/route-list.component.html, src/app/route/route-list/route-list.component.ts, src/app/shared/http.config.ts
=> 25 paging  scrollbar tras

src/app/route/route-edit/route-edit.component.ts, src/app/route/routes/routes.component.css, src/app/route/routes/routes.component.html, src/app/shared/map/map.component.ts, src/app/shared/side-panel/side-panel.component.ts
już naprawione prosze o accepta
~po wybraniu ścieżki, kliknięciu edit i od razu save jest ok  - znowu wyświetla się side panel z tą trasą~
~po wybraniu ścieżki, kliknięciu edit i od razu cancel jest prawie ok - side panel nie wiem czemu się zamyka ale trasa wciązsię zgadza.~
~nie rozumiem czemu tak jest skoro i cancel i save wywołują tą samą funkcję goBack
mógłby ktoś na to zerknąć?~
=> navigation bug exterminated

src/app/app.component.html, src/app/header/header.component.css, src/app/header/header.component.html, src/app/header/header.component.ts, src/app/route/route-detail/route-detail.component.html, src/app/route/route-list/route-list.component.html, src/app/route/route-list/route-list.component.ts, src/app/route/routes/routes.component.html, src/app/route/routes/routes.component.ts
naprawiłem cssa i htmla. Teraz wszystko dostosowuje się do wymiarów urządzeń. Musiałem zmienić headera na brzydszego ale przynajmniej wszystko sie miesci. Nad wyglądem popracuje sie potem, na razie ważne zeby było responsywne i działające 
BŁAGAM NIE SMIEJCIE SIE ŻE BRZYDKO JA NAPRAWDE SIE STARAM NIE WIEM JAK ŁADNIEJ ZROBIĆ TEN HEADER JEST TAKI BRZYDKI 😭😭😭😭😭😭😭😭😭😭😭😭 headera sie potem dopracuje wazne ze po prostu dziala
=> view fixed

src/app/map-location/map-location-edit/map-location-edit.component.ts, src/app/route/route-edit/route-edit.component.html, src/app/route/route-edit/route-edit.component.ts
=> Cancel przy dodawaniu route juz dziala

package-lock.json, package.json, src/app/auth/auth.service.ts
nowe metody w auth service:
**getUserId(): string | null { }** - dekoduje wam z jwt userID ktorego mozecie uzywac
**isLoggedIn(): boolean { }** - sprawdza czy token jest przedawniony lub go nie ma, na podstawie tego mozna przekierowac uzytkownika na logowanie @Kondziow chyba ty to miales do zrobienia
**isTokenExpired(token: string): boolean {}** - pomocnicza metoda do isLoggedIn raczej wam nie potrzebna
=> FEATURE: isLoggedIn, getUserID

src/app/route/route-list/route-list.component.html, src/app/route/route-list/route-list.component.ts, src/app/route/route.service.ts
Filtrować trasy można na 2 sposoby:
1. Poprzez pole input
2. Poprzez queryParam -> routeName
Oba sposoby tworzą nam queryParam o takiej nazwie w ścieżce gdy filtrujemy po jakiejś nazwie, natomiast gdy nie filtrujemy (ta nazwa to ""), to queryParam znika ze ścieżki.
Dodatkowo dla wygody dodalem przycisk usuwajacy filtrowanie
Ma ktos pomysl jak rozwiazac problem ze przy dodawaniu queryParams uzywam caly czas takiego samego kodu? Jak to wpakowac w jakas funkcje zeby dzialalo? Probowalem cos na zasadzie:
Ale nie dziala
Zanim będzie merge będę wdzięczny za testy (po prostu się pobawcie 3 min) i może jakieś sugestie co jeszcze poprawić
=> 58 filtrowanie tras

src/app/header/header.component.css, src/app/header/header.component.html, src/app/route/route-detail/route-detail.component.html, src/app/route/route-info/route-info.component.css, src/app/route/route-info/route-info.component.html, src/app/route/route-list/route-list.component.css, src/app/route/route-list/route-list.component.html, src/app/route/route-list/route-list.component.ts, src/app/route/routes/routes.component.css, src/app/route/routes/routes.component.html, src/app/shared/http.config.ts, src/app/user/log-in/log-in.component.css, src/app/user/log-in/log-in.component.html
taki header ze wam zęby wypadną
=> Poprawa wygladu headera

src/app/app.component.ts, src/app/audio/audio.model.ts, src/app/audio/audio.service.ts, src/app/header/header.component.css, src/app/header/header.component.html, src/app/header/header.component.ts, src/app/map-location/map-location-info-window/map-location-info-window.component.css, src/app/map-location/map-location-info-window/map-location-info-window.component.html, src/app/map-location/map-location-info-window/map-location-info-window.component.ts, src/app/map-location/map-location-list/map-location-list.component.css, src/app/map-location/map-location-list/map-location-list.component.html, src/app/map-location/map-location-list/map-location-list.component.ts, src/app/route/route-detail/route-detail.component.html, src/app/route/route-detail/route-detail.component.ts, src/app/route/route-info/route-info.component.ts, src/app/route/route-list/route-list.component.ts, src/app/route/routes/routes.component.css, src/app/route/routes/routes.component.ts, src/app/shared/map/map.component.html, src/app/shared/map/map.component.ts, src/app/shared/map/map.service.ts, src/app/shared/screen-size.service.ts, src/app/shared/side-panel.service.ts, src/index.html, src/main.ts
szalom
dodalem: 
lista map location po kliknieciu map detail
focus na marker po wybraniu map location z listy 
audio service
fetchowanie audiosow po kliknieciu markera
po zrobieniu tych rzeczy mam kilka nowych taskow wiec dodam je do tablicy
------ update --------
dodałem duzo innych rzeczy: 
resize service, changing map location list, adding map location details (photo info audio-list) as a grid, changing map location marker, adding animation to clicked map location, adding different closing/opening procedures depending on device size
KONRAD PROSZE DODAJ TEN MAP LOCATION LIST DO SWOJEGO EDIT ROUTE KOMPONENTU BO NIE WIEM CZEMU NIE STWORZYLES WCZESNIEJ KOMPONENTU MAP LOCATION LIST. POTEM DODASZ ZE W TEJ LISCIE MAP LOCATION BEDZIE MOZLIWOSC EDYCJI (PRZYCISK PRZY KAZDYM MAP LOCATION KTORY …
=> 68 odtwarzenie audio punktw

src/app/map-location/map-location-edit/map-location-edit.component.html, src/app/map-location/map-location-edit/map-location-edit.component.ts, src/app/map-location/map-location.service.ts
dodawanie zdjec do map location
=> 65 dodawanie zdjec do map location

src/app/route/route-info/route-info.component.ts, src/app/route/route-list/route-list.component.ts, src/app/route/route.service.ts, src/app/user/user-profile/user-profile.component.ts, src/app/user/user.service.ts
1. User profile wyswietla dane aktualnego usera
2. Metoda isUserMode() sprawdzajaca czy wlaczona jest zakladka Your Routes jest teraz w RoutesService, co pozwala uniknac uzywania tego samego kodu kilka razy w kilku plikach
=> 76 profil usera jego dane powinno wyswietlac

src/app/route/route.service.ts, src/app/user/user.model.ts
Tak jak w tytule. 
W klasie user login oraz username zmienione na optional zeby w routeService mozna bylo do route dolaczyc tylko id usera, a nie trzeba bylo zaciagac calego usera z backendu. Alternatywnie mozna tego usera zaciagac np przy logowaniu i trzymac go np w user Service?
=> Aktualny user jest przypisywany do nowo tworzonych tras

package-lock.json, package.json, src/app/map-location/map-location-info-window/map-location-info-window.component.css, src/app/map-location/map-location-info-window/map-location-info-window.component.html, src/app/map-location/map-location-list/map-location-list.component.html, src/app/map-location/map-location-list/map-location-list.component.ts, src/app/route/route-detail/route-detail.component.css, src/app/route/route-detail/route-detail.component.html, src/app/route/route-info/route-info.component.css, src/app/route/route-info/route-info.component.html, src/app/route/route-info/route-info.component.ts, src/app/route/route-list/route-list.component.css, src/app/route/route-list/route-list.component.html, src/app/route/route-list/route-list.component.ts, src/app/user/user-profile/user-profile.component.css, src/app/user/user-profile/user-profile.component.html, src/app/user/user-profile/user-profile.component.ts
Szalom bracia i siostry 
poprawilem widok kolejnych komponentow
poprawa wyglądu user profile
dodanie informacji o autorze do tras
zmniejsz enie czestotliwosci mrygania, 
dwa razy klikniety route w route list przenosi do details
dodalem  opisy przycisków
zmienilem troche wyglad filtra
usunalem kilka bledow 
dodalem glupie animacje
=> 85 poprawki w wygldzie i naprawa bdw map location

src/app/app-routing.module.ts, src/app/map-location/map-location-edit/map-location-edit.component.html, src/app/map-location/map-location-edit/map-location-edit.component.ts, src/app/map-location/map-location-list/map-location-list.component.html, src/app/map-location/map-location-list/map-location-list.component.ts, src/app/map-location/map-location.service.ts, src/app/map-location/point-select-map/point-select-map.component.ts, src/app/map-location/point-select-map/point-select-map.service.ts, src/app/route-map-location/route-map-location.service.ts, src/app/route/route-detail/route-detail.component.html, src/app/route/route-detail/route-detail.component.ts, src/app/route/route-edit/route-edit.component.html, src/app/route/route-edit/route-edit.component.ts, src/app/route/route-info/route-info.component.html, src/app/route/route-info/route-info.component.ts, src/app/route/route-list/route-list.component.html, src/app/route/route-list/route-list.component.ts
Troche tych zmian bylo nie, niech ktos sprawdzi czy wszystko dziala jak nalezy, i w razie czego naprawie. 
PS: trzeba najpierw zrobic merge backendu bo dalem poprawki
ogolnie co myslicie o takim stylu commitow? Nie wiem wgl czy na pewno dobrze tego uzywam XD ale wydaje sie fajne czytelniejsze
----------------------
1. route edit nie jest responsywny
2. map location list lepiej zeby byl uzyty ponownie jako komponent (map location list) (uwaga na event listenery)
3. po dodaniu listy map locations, obok każdego z nich przycisk do edycji tego map location
4. po zapisaniu zmian lepsze przekierowanie - np do details tej trasy albo przynajmniej na liste routow usera a nie wszystkich
5. dodanie opcji edycji w map details w my routes (czyli tylko dla naszych tras i punktów) - przycisk do edycji …
=> 93 poprawa route edit

src/app/map-location/map-location-list/map-location-list.component.html, src/app/map-location/map-location-list/map-location-list.component.ts, src/app/map-location/map-location.service.ts
TESTOWAC NA NOWYM BACKENDZIE (Na razie nadal wisi na niego PR)
Jak jest punkt tylko do jednego route to usuwamy punkt. Jak jest do kilku to usuwamy ta encje RouteMapLocation
Problemem jest przekierowanie po wcisnieciu delete. Bez przekierowania nie moze byc, bo sie lista punktow nie odswieza i nadal widac usuniety juz punkt (Moze jakos to refreshowac? Probowalem wywolac drugi raz fetchMapLocation ale nie dzialalo. Mozliwe ze po prostu zle to robilem XD). Aktualnie jest cofniecie do yourRoutes/list, ale no trzebaby to chyba zmienic.
=> 96 moliwo usunicia map location z trasy

src/app/map-location/map-location-edit/map-location-edit.component.html, src/app/route/route-list/route-list.component.ts
Stronicowanie naprawione, działa dobrze.
Przy okazji napisa 'adding new point' zmieniony na 'editing map loction' przy edycji map location. Chyba ze macie lepszy pomysl na ten napis?
=> 98 stronicowanie przy filtrowaniu tras

src/app/shared/map/map.component.ts
=> New Marker

src/app/map-location/map-location-list/map-location-list.component.html, src/app/map-location/map-location-list/map-location-list.component.ts, src/app/route-map-location/route-map-location.service.ts, src/app/route/route-list/route-list.component.html, src/app/route/route-list/route-list.component.ts, src/app/shared/map/map.component.ts
No ogolnie chyba dziala. Sposob Oskara, czyli z poziomu szczegolow trasy mozemy dodac punkt do naszej trasy.
Jak macie chwile to potestujcie czy nie ma bugow zadnych
=> feat: can add existing point (map location) to your route

src/app/map-location/map-location-info-window/map-location-info-window.component.ts, src/app/map-location/map-location-list/map-location-list.component.css, src/app/map-location/map-location-list/map-location-list.component.html, src/app/map-location/map-location-list/map-location-list.component.ts, src/app/map-location/map-location-modal/map-location-modal.component.css, src/app/map-location/map-location-modal/map-location-modal.component.html, src/app/map-location/map-location-modal/map-location-modal.component.ts, src/app/route/route-detail/route-detail.component.html, src/app/route/route-detail/route-detail.component.ts, src/app/route/route-info/route-info.component.css, src/app/route/route-info/route-info.component.html, src/app/route/route-info/route-info.component.ts, src/app/route/route-list/route-item/route-item.component.ts, src/app/route/route-list/route-list.component.html, src/app/route/route-list/route-list.component.ts, src/app/shared/modal/modal.component.css, src/app/shared/modal/modal.component.html, src/app/shared/modal/modal.component.ts, src/app/shared/modal/modal.service.ts, src/app/user/user-profile/user-profile.component.css, src/styles.css
- added custom-made universal reusable modal 
- moved map location info to the modal 
- map location info is now accessible through map info window as well as map location list 
- changed appereance of map location list items buttons and route edit button
- changed route info component so there is less clutter
- removed not working go back button 
- fixed route list details button and added animations to it
=> Wtg 6 map location info window details refactoring

src/app/app-routing.module.ts, src/app/map-location/map-location-edit/map-location-edit.component.ts
1. Now you can edit your new point immediately after adding it 
2. Now you can't edit routes after typing by hand 'routes/:id/edit'
=> Wtg 16 no ability to edit map location after adding it fix

src/app/map-location/map-location-modal/map-location-modal.component.html, src/app/map-location/map-location-modal/map-location-modal.component.ts, src/app/route/route-info/route-info.component.html, src/app/route/route-info/route-info.component.ts, src/app/route/route-list/route-list.component.css, src/app/route/route-list/route-list.component.html, src/app/shared/snackbar/snackbar-type.ts, src/app/shared/snackbar/snackbar.component.css, src/app/shared/snackbar/snackbar.component.html, src/app/shared/snackbar/snackbar.component.ts, src/app/shared/snackbar/snackbar.service.ts
- added universal snackbar component and service for error messages and communicating with the user (for example after successful route creation)
- we can call service with 2 params: message and type to create a snackbar anywhere in app
- also fixed routing problem in route info mentioned by @Kondziow  in last PR and added borders to route list items and fixed some buttons
https://github.com/user-attachments/assets/ec2615a9-527e-4a0d-a1fa-1ba1f939bac9
=> Wtg 27 create universal snackbar

src/app/app.component.html, src/app/header/header.component.css, src/app/map-location/map-location-edit/map-location-edit.component.css, src/app/map-location/map-location-edit/map-location-edit.component.html, src/app/map-location/map-location-edit/map-location-edit.component.ts, src/app/route/route-edit/route-edit.component.html, src/app/route/route-list/route-list.component.html
1. Nav bar is now always visible and don't scroll up
2. Map location edit component looks better
=> Wtg 26 enhance map location edit view

src/app/app-routing.module.ts, src/app/map-location/map-location-edit/map-location-edit.component.ts, src/app/map-location/map-location-list/map-location-list.component.ts, src/app/route/route-edit/route-edit.component.ts, src/app/shared/guards/can-deactivate-form-guard.service.ts, src/app/shared/guards/can-deactivate-guard.service.ts
- fixed bug with redirect after adding new point mentioned by Janek
- added confirmation after deletion map location & route 
- added confirmation after exiting edit  map location & route
- added confirmation after exiting add new  map location & route
- created jira ticket to move delete map location to edit form
=> Wtg 51 alert when leaving edit without saving
